### PR TITLE
Reqs

### PR DESCRIPTION
**Pull request by JustScreaMy**
Added `requirements.txt` so makes #8 easier. If you use different version, please respond with them to this PR
Added `./vscode` to `.gitignore` because it wasn't ignoring my vscode folder

### CODE REVIEW

**Comment by adam5847** [comment]
Thanks for PR, I use different PyQt5-sip version 12.8.1

**Comment by frenzymadness** [comment]
I don't see the content of the requirements.txt, why does github think it's a binary file? Is it possible that it has some non-utf-8 encoding?

**Comment by JustScreaMy** [comment]
It had encoding UTF-16 LE for some unknown reason

**Review by frenzymadness — APPROVED** [review]
It looks good to me but the final approval is up to the main maintainer.

**Pull request merged**
